* Failures of encryptsetup
** TODO Failure in pulling down images
#+BEGIN_ASCII
Error pulling image (latest) from registry.hub.docker.com/cloudfleet/blimp-doveshed, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
#+END_ASCII 

We are currently pulling down complete images as part of docker reboot.

*** Suggestion from Christoph
#+BEGIN_ASCII
@doublemalt re: rollback ... maybe set up a retry that is only cancxceled on success?
#+END_ASCII

We need to sort out exit status from sub-scripts.

** Too small /var/docker/lib?
#+BEGIN_ASCII
Filesystem          Size  Used Avail Use% Mounted on
/dev/sda1            31G  4.9G   25G  17% /
udev                 10M     0   10M   0% /dev
tmpfs               403M   22M  381M   6% /run
tmpfs              1006M  132K 1005M   1% /dev/shm
tmpfs               5.0M  4.0K  5.0M   1% /run/lock
tmpfs              1006M     0 1006M   0% /sys/fs/cgroup
tmpfs               202M   12K  202M   1% /run/user/1000
/dev/sdb1            30G   44M   28G   1% /mnt/storage-key
/dev/mapper/cf-str  5.3G  834M  4.0G  18% /mnt/storage
/dev/mapper/cf-str  5.3G  834M  4.0G  18% /var/lib/docker
#+END_ASCII
No, just my problem in mixing up key/str


** crypt upgrade takes a long time
crypt_upgrade in vbox with USB 3 took ~50 minutes
User won't necessarily know what is going on, as Blimp is just sitting
there.  Power cycle is potentially fatal.

** /opt/cloudfleet/data/logs disappeared

vbox upgrade failed to have logs 

** Why are we using 'service' instead of 'systemctl' ?
systemd uses systemctl

* vbox failure to start containers

#+BEGIN_ASCII
2015-11-25 14:54:31 Starting containers ... 
==============================
Creating blimp_conduit_1...
Creating blimp_doveshed_1...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 39, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 495, in up
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 265, in up
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 369, in execute_convergence_plan
    do_build=do_build,
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 276, in create_container
    return Container.create(self.client, **container_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/container.py", line 42, in create
    response = client.create_container(**options)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 245, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 252, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/lib/python2.7/dist-packages/docker/clientbase.py", line 128, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/clientbase.py", line 83, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
==============================
2015-11-25 14:55:59  Started containers. 

#+END_ASCII
* vbox failure to start
#+BEGIN_ASCII
2015-11-25 15:11:38 Starting containers ... 
==============================
Creating blimp_conduit_1...
Creating blimp_doveshed_1...
Creating blimp_mailpileeasye_1...
Creating blimp_musterroll_1...
Creating blimp_radicale_1...
Creating blimp_mailbox_1...
Creating blimp_cockpit_1...
Creating blimp_wellknown_1...
Creating blimp_nginx_1...
Creating blimp_pagekite_1...
Cannot find child for /blimp_pagekite_1
==============================
#+END_ASCII




